[project]
name = "athena-assignment"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=1.26.4,<2.1.0",
    "pandas>=2.2.2",
    "scikit-learn",
    "matplotlib",
    "jupyter>=1.1.1",
    "notebook>=7.5.3",
    "ipython>=9.9.0",
    "python-dotenv",
    "statsmodels>=0.14.6",
    "scipy>=1.17.0",
    "seaborn>=0.13.2",
    "pyarrow>=15.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/athena_analyze", "src/utils"]

[tool.uv]
dev-dependencies = ["pytest", "ruff"]
