data:
  raw: "../data/raw"
  experiment: "../data/experiment"
preprocess:
  split_date:
    train_start: "2016-07-01 00:00:00"
    train_end: "2018-02-01 13:59:59"
    test_start: "2018-02-01 14:00:00"
    test_end: "2018-06-26 19:00:00"
